---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devops-app
spec:
  type: ClusterIP  # קובע שהשירות יהיה זמין רק בתוך הקלאסטר
  selector:
    app: backend  # תואם לתוויות (labels) שהגדרנו ב-Deployment
  ports:
    - name: http       # <--- הוסף את השורה הזו
      protocol: TCP
      port: 5000 # הפורט שזה Service קלאסטר
      targetPort: 5000 # הפורט שבו הפוד עצמו (Flask) מאזין
