# ==============================================================================
# 1. חיבור זהויות (IRSA):
# קישור בין זהות הפוד בקוברנטיס להרשאות ניהול
# (IAM Role) ב-AWS.
# ==============================================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: devops-app
