# ==============================================================================
# 1. זהות השירות (Metadata):
# יצירת כתובת קבועה
# ('backend-service') בתוך הקלאסטר.
# ==============================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devops-app
  labels:
    app: backend
spec:
# ==============================================================================
# 2. סוג וניתוב (Type & Selector):
# שירות פנימי וסגור
# (ClusterIP)
# המנתב תעבורה לפודי ה-
# Backend.
# ==============================================================================
  type: ClusterIP
  selector:
    app: backend
# ==============================================================================
# 3. מיפוי פורטים (Ports):
# קבלת בקשות בפורט 5000
# והעברתן לפורט
# 5000
# בקונטיינר
# (Flask).
# ==============================================================================
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000