# ==============================================================================
# 1. חיבור זהויות (IRSA):
# קישור בין זהות הפוד בקוברנטיס להרשאות ניהול
# (IAM Role) ב-AWS.
# ==============================================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: devops-app
  annotations:
    # הקסם קורה כאן: התיוג שמורה לקוברנטיס להזריק את הרשאות ה-
    # IAM
    # היישר אל תוך הפוד
    # yamllint disable-line rule:line-length
    eks.amazonaws.com/role-arn: "arn:aws:iam::544471418394:role/aviv-mission-iam-role-v2"