---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: devops-app
  annotations:
    # כאן אנחנו קושרים את ה-IAM Role של AWS ישירות לזהות בתוך קוברנטיס (IRSA)
    # yamllint disable-line rule:line-length
    eks.amazonaws.com/role-arn: "arn:aws:iam::544471418394:role/aviv-mission-iam-role-v2"
