# ==============================================================================
# 1. יצירת זהות (ServiceAccount):
# הגדרת זהות ייעודית ומוגבלת עבור פודי ה-
# Frontend.
#כדי להפריד את זהות ה-
# Frontend
# מזהויות של רכיבים אחרים כמו ה-
# Backend,
# ובכך לצמצם את מרחב הפגיעה למינימום האפשרי במקרה של מתקפת סייבר.
# ==============================================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: devops-app