---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: devops-app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: worker-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: worker
          # התגית תוחלף דינמית על ידי סקריפט ה-bash
          image: 544471418394.dkr.ecr.us-east-1.amazonaws.com/mission-worker:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: app-config
            # קריאה לשני הסודות הנפרדים שלנו
            - secretRef:
                name: db-app-secrets
            - secretRef:
                name: flask-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
