# ==============================================================================
# 1. הגדרות כלליות (Metadata & Replicas):
# פריסת רכיב הרקע
# (Worker)
# בעותק יחיד.
# ==============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: devops-app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
# ==============================================================================
# 2. הרשאות פוד (Pod Security & SA):
# הפעלת זהות
# AWS,
# חסימת גישה ל-
# API
# והרצה כ-Non-Root.
# ==============================================================================
      serviceAccountName: worker-sa
      automountServiceAccountToken: false  # <-- חסימת גישה למערכת קוברנטיס
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
# ==============================================================================
# 3. הגדרת קונטיינר וסביבה (Container Spec):
# משיכת הקוד והזרקת הגדרות וסודות מהקלאסטר.
# ==============================================================================
      containers:
        - name: worker
          # התגית תוחלף דינמית על ידי סקריפט ה-bash
          image: 544471418394.dkr.ecr.us-east-1.amazonaws.com/mission-worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            # קריאה לשני הסודות הנפרדים שלנו
            - secretRef:
                name: db-app-secrets
            - secretRef:
                name: flask-secret
# ==============================================================================
# 4. הקשחת קונטיינר (Security Context):
# חסימת הסלמת הרשאות וניקוי יכולות מערכת לינוקס.
# ==============================================================================
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
# ==============================================================================
# 5. ניהול משאבים (Resource Limits):
# הגדרת רף מינימום ומקסימום למניעת צריכת יתר.
# ==============================================================================
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"