# ==============================================================================
# 1. חיבור זהויות (IRSA):
# קישור בין זהות ה-
# Worker
# בקוברנטיס להרשאות
# (IAM Role) ב-AWS.
# ==============================================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: devops-app
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::544471418394:role/aviv-mission-worker-role"
