---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: devops-app
  annotations:
    # yamllint disable-line rule:line-length
    eks.amazonaws.com/role-arn: "arn:aws:iam::544471418394:role/aviv-mission-iam-role-v2"
