# ==============================================================================
# 1. סביבת עבודה מבודדת (Namespace):
# יצירת מתחם לוגי נפרד
# ('devops-app')
# עבור משאבי הפרויקט.
# ==============================================================================
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-app
  labels:
    name: devops-app
    environment: dev