{
 "title": "Application Overview (Page 3 SLI/SLO)",
 "tags": [
  "application",
  "backend"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Availability (SLO: 99%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"2..|3..\"}[5m])) / sum(rate(flask_http_request_total[5m]))"
    }
   ]
  },
  {
   "title": "Latency p95 & p99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99 Latency"
    }
   ]
  },
  {
   "title": "Traffic & Errors (5xx Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m]))",
     "legendFormat": "Total Requests / sec"
    },
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx Errors / sec"
    }
   ]
  },
  {
   "title": "Business Metrics: Infrastructure Provisioning",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "business_infra_created_total", "legendFormat": "Instances Created" },
    { "expr": "business_infra_deleted_total", "legendFormat": "Instances Deleted" }
   ]
  }
 ]
}