apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: observability-traffic-policy
  namespace: observability
spec:
  podSelector: {} # החוק יחול על כל הפודים בתוך observability
  policyTypes:
    - Ingress
  ingress:
    # 1. היתר לתקשורת פנימית בתוך ה-Namespace
    - from:
        - podSelector: {}

    # 2. היתר לגישה חיצונית (עבור ה-LoadBalancer של גרפנה)
    - ports:
        - port: 3000
          protocol: TCP
        - port: 9090 # פורט ברירת מחדל של פרומתיאוס למקרה של דיבוג
        - port: 9093 # פורט של Alertmanager