# ==============================================================================
# 1. חיבור לספק (SecretStore):
# הגדרת ההתחברות המאובטחת ל-
# AWS Secrets Manager.
# כדי לקבוע איזה סוד ספציפי ישלוף מקטלוג הסודות ב-
# AWS ,
# לרענן אותו אוטומטית כל דקה למקרה שהסיסמה תשתנה, וליצור ממנו אובייקט מקומי בשם
# db-app-secrets
# שהפודים יוכלו לקרוא ממנו.
# ==============================================================================
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: devops-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: backend-sa
# ==============================================================================
# 2. סנכרון הסוד (ExternalSecret):
# משיכת הסיסמה מאמזון והפיכתה ל-
# Secret מקומי בקלאסטר.
# כדי להדריך את הקלאסטר לאיזה איזור בענן לפנות
# - us-east-1
# ואיזו ״תעודת זהות״ להציג - ה-
# SA
# של ה-
# Backend
# שיש לו הרשאות
# IAM,
#  כדי שאמזון יסכים לדבר איתו.
# ==============================================================================
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-app-secrets
  namespace: devops-app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: db-app-secrets
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: aviv-db-password-secret