---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: devops-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: backend-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-app-secrets
  namespace: devops-app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: db-app-secrets
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: aviv-db-password-secret
