# ==============================================================================
# הגדרת סביבה (Namespace):
# יצירת מתחם מבודד עבור שרת ה-Jenkins
# מה הבלוק עושה: מורה לקוברנטיס ליצור סביבה לוגית נפרדת בשם
# 'jenkins'.
# למה צריך את זה: הפרדה קריטית בארכיטקטורה. ה-
# Namespace
# מוודא שרכיבי ה-
# CI/CD
# מבודדים לחלוטין משאר המערכת כמו האפליקציה או הניטור, מה שמשפר את האבטחה והסדר בקלאסטר.
# ==============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins